platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'dVox' do
  
   use_frameworks!
   
   pod 'web3swift', :git => 'https://github.com/lvyikai/web3swift.git', :branch => 'develop'

   pod 'Starscream', '~> 3.1.1'
 
   pod 'Firebase/Core'
   pod 'Firebase/Messaging'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Crashlytics'
   pod 'Firebase/DynamicLinks'


   pod 'NavigationStack'
   
end
