platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'dVox' do
  
   use_frameworks!
   
   pod 'web3swift'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Crashlytics'
   pod 'Firebase/DynamicLinks'
   
end
